### ISSUE TITLE
Bluetooth Pairing Failure

### ISSUE THREAD

**Issue by EdyGH36** [pklaus/canoremote#1]
Hello!

I'm currently trying to build an automated photogrammetry robot based on this YouTube video, https://www.youtube.com/watch?v=dyPn5lmq9B4. Instead of Arduino, it will be based on Raspberry Pi which means that I'm a Python beginner. The camera I'm using right now is a mirrorless Canon M50. At first, the effective way to control the camera is to use gphoto2 since it's easily done by USB until someone really expected the camera to be wireless controlled by Bluetooth so the USB should be used for automatic upload into another computer.
This repository you have right now must have been my lucky day. I downloaded it and try to run the script as written on your readme. It did something but it didn't paired successfully.

On the Thonny IDE console, the error shows: 
```
Traceback (most recent call last):
File "/home/pi/Downloads/canoremote-main/test.py", line 33, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/Downloads/canoremote-main/test.py", line 13, in run
    await cr.initialize()
  File "/home/pi/Downloads/canoremote-main/canoremote.py", line 32, in initialize
    await self.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 106, in connect
    raise BleakError("Client is already connected")
bleak.exc.BleakError: Client is already connected
```
And when looking on the camera, the message shows when after the pair attempt:

> Connection target not found

I would like to know more what's the exact cause of the issue? Perhaps an auto disconnect to be written?
Thank you for understanding!

**Comment by tarneaux** [comment]
Same problem here, have you managed to make it wok?

**Comment by bikmazer** [comment]
Please remove connect command. It sounds a little crazy, but it worked.
```Python
async def initialize(self):
        #await self.connect(timeout=2) 
        print("Services:")
        for service in self.services:
            print(service) 
            for char in service.characteristics:
                print("  ",char)
                if char.uuid == UUIDCharacteristic.Pairing:
                    pairingChar = char
                if char.uuid == UUIDCharacteristic.Event:
                    eventChar = char
 
        print("Characteristics:")
        print(pairingChar)
        print(eventChar)
        #self.services = await self.get_services() 
        #await self.get_services(timeout=5)
        data = bytearray([3, ] + list(map(ord, DEVICE_NAME)))
        print(data)
        await self.write_gatt_char(IntCharacteristic.Pairing, data)
        #await self.write_gatt_char("00050002-0000-1000-0000-d8492fffa821", data, response=True,timeout=5)


    async def state(self, mode: Mode, button: Button = 0):
        data = bytearray([mode | button])
        await self.write_gatt_char(IntCharacteristic.Event, data)
        #await self.write_gatt_char("00050003-0000-1000-0000-d8492fffa821", data, response=True,timeout=5)


```

**Comment by nm17** [comment]
@bikmazer You should probably make a fork of this repo, since it is not maintained

**Comment by bikmazer** [comment]
I forked and serviced it, FYI.

**Comment by bikmazer** [comment]
I forked and maintained it, FYI.

**Comment by bikmazer** [comment]
@nm17 I forked and maintained it, FYI.

@pklaus
